//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public string PersonID { get; set; }
        public Nullable<System.DateTime> TimeStartRent { get; set; }
        public Nullable<System.DateTime> TimeEndRent { get; set; }
        public Nullable<int> PaymentPerMonth { get; set; }
        public string PictureOfContract { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
