//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string VehicleID { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Picture { get; set; }
        public string PersonID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
