//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterPayment
    {
        public int RoomID { get; set; }
        public System.DateTime DatePay { get; set; }
        public Nullable<double> Volume { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
